// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortfolioManagementMvc.Data;

#nullable disable

namespace PortfolioManagementMvc.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("PortfolioManagementMvc.Models.AssetModel", b =>
                {
                    b.Property<int>("AssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetSymbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Forecast2028")
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetYear")
                        .HasColumnType("INTEGER");

                    b.HasKey("AssetId");

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            AssetId = 1,
                            AssetName = "Garanti Bankasi",
                            AssetSymbol = "GARAN",
                            CurrentPrice = 0m,
                            Forecast2028 = 0m,
                            TargetYear = 2028
                        },
                        new
                        {
                            AssetId = 2,
                            AssetName = "Darphane Altin Sertifikasi",
                            AssetSymbol = "ALTINS1",
                            CurrentPrice = 0m,
                            Forecast2028 = 0m,
                            TargetYear = 2028
                        },
                        new
                        {
                            AssetId = 3,
                            AssetName = "Anadolu Sigorta",
                            AssetSymbol = "ANSGR",
                            CurrentPrice = 0m,
                            Forecast2028 = 0m,
                            TargetYear = 2027
                        });
                });

            modelBuilder.Entity("PortfolioManagementMvc.Models.TransactionModel", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("InvestorEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InvestorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelectedAssetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TransactionId");

                    b.HasIndex("SelectedAssetId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("PortfolioManagementMvc.Models.TransactionModel", b =>
                {
                    b.HasOne("PortfolioManagementMvc.Models.AssetModel", "Asset")
                        .WithMany("Transactions")
                        .HasForeignKey("SelectedAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("PortfolioManagementMvc.Models.AssetModel", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
